name: content_cli
description: Content tooling for Palabra.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  palabra:
    path: ../../
  path: ^1.9.0

dev_dependencies:
  very_good_analysis: ^5.1.0
